### ISSUE TITLE
Aint 1Mil no more??

### ISSUE THREAD

**Issue by iDevYoyo** [shrekshrek214/Stand-Money-Lua#3]
so i updated to 1.5 and there is not 1Mil, did rockstar detected it??

**Comment by vladislav2077** [comment]
sure. from 13.06.2024 it starts to be detected21.06.2024, 22:28, "iDevYoyo" ***@***.***>:
so i updated to 1.5 and there is not 1Mil, did rockstar detected it??

**Comment by themilkman554** [comment]
R* changed the limit from 1m to 180k and it's marked as risky cause there may have been bans from it.  The 40 mil and other transactions may still be fine.

**Comment by iDevYoyo** [comment]
May you have a discord server or something to get the news of detects and script..??

My user is 1yoyo, add me if you want
